[Config]
mode=voltage
data_dir=/home/ark/.config/batteryplus
V_FULL_CHG = 4050  // 充电时 100% 电压 (mV)
V_FULL_DIS = 4000  // 放电时 100% 电压
V_EMPTY_CHG = 3400 // 充电时 0% 电压
V_EMPTY_DIS = 3250 // 放电时 0% 电压
INTERNAL_INTERVAL_S = 15  // 内部计算间隔
WRITE_INTERVAL_S = 120    // 写文件间隔